DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS experiment;
DROP TABLE IF EXISTS trayData;


CREATE TABLE user (
  userid INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL
);

CREATE TABLE trayData (
  trayid INTEGER PRIMARY KEY AUTOINCREMENT,
  trayName TEXT NOT NULL,
  wellPositions FLOAT NOT NULL
);

CREATE TABLE experiment (
  experimentid INTEGER PRIMARY KEY AUTOINCREMENT,
  tray INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  info TEXT NOT NULL,
  instructions TEXT NOT NULL, 
  authorID INTEGER NOT NULL
);
